{
 "title": "Docker Dashboard",
 "description": "Docker Monitoring Template",
 "tags": [
  "prometheus",
  "cadvisor"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instancelist",
    "query": "label_values({job='docker'},instance)"
   },
   { "name": "interfacelist", "query": "eth0|eth1, eth0, eth1" },
   {
    "name": "container_names",
    "query": "label_values({instance=~\"$instancelist\"},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Container(s)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=~\"$instancelist\", name=~\".+\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Container(s)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=~\"$instancelist\", name=~\".+\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_cpu_user_seconds_total{instance=~\"$instancelist\",image!=\"\"}) by (instance)"
    }
   ]
  },
  {
   "title": "container swap usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_swap{instance=~\"$instancelist\",image!=\"\"})  / ( 1024 * 1024 )"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total{image!=\"\"}[1m] ) )) / count(node_cpu{mode=\"system\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{instance=~\"$instancelist\"} - container_fs_usage_bytes{instance=~\"$instancelist\"}) / sum(container_fs_limit_bytes{instance=~\"$instancelist\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{instance=~\"$instancelist\",image!=\"\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{instance=~\"$instancelist\",image!=\"\"}[1m])) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Instance Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$instancelist\",image!=\"\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{instance=~\"$instancelist\",image!=\"\"}) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Instance Network Input",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": " rate(container_network_receive_bytes_total{id=\"/\",instance=~\"$instancelist\",interface=~\"$interfacelist\" }[1m] ) ",
     "legendFormat": "{{ instance }} {{ interface }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{instance=~\"$instancelist\",image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Instance Network Output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": " rate(container_network_transmit_bytes_total{id=\"/\",instance=~\"$instancelist\",interface=~\"$interfacelist\" }[1m] ) ",
     "legendFormat": "{{ instance }} {{ interface }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{instance=~\"$instancelist\",image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}