{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "topics",
    "label": "Topics",
    "query": "activities|records, activities, records"
   },
   {
    "name": "instances",
    "label": "InstanceList",
    "query": "kafka1:7071|kafka2:7071|kafka3:7071,kafka1:7071,kafka2:7071,kafka3:7071"
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"kafka\",instance=~\"[[instances]]\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\",instance=~\"[[instances]]\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\",instance=~\"[[instances]]\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message In",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages In Per Topic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Messages/s" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=~\"$topics\"}[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message In Per Broker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 14, "x": 10, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{job='kafka',topic=~\"$topics\",instance=~\"[[instances]]\"}[5m])",
       "legendFormat": "{{topic}}, {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Bytes In / Out", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic=~\"$topics\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Total Per Topic with Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic=~\"$topics\",instance=~\"[[instances]]\"}[1m])",
     "legendFormat": "{{topic}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic=~\"$topics\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic=~\"$topics\",instance=~\"[[instances]]\"}[5m])",
     "legendFormat": "{{topic}}, {{instance}}"
    }
   ]
  },
  { "title": "Fetch Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Fetch Request Total Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_totalfetchrequests_total{job='kafka',topic=~\"$topics\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Request Total Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_totalfetchrequests_total{job='kafka',topic=~\"$topics\",instance=~\"[[instances]]\"}[1m])",
     "legendFormat": "{{topic}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Requests Total Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_failedfetchrequests_total{job='kafka',topic=~\"$topics\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Requests Total Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_failedfetchrequests_total{job='kafka',topic=~\"$topics\",instance=~\"[[instances]]\"}[1m])",
     "legendFormat": "{{topic}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Producer Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producer Request Total Per Topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_totalproducerequests_total{job=\"kafka\",topic=~\"$topics\"}[1m]))",
       "legendFormat": "{{topic}}, {{instance}}"
      }
     ]
    },
    {
     "title": "Failed Producer Request Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_brokertopicmetrics_failedproducerequests_total{job='kafka',topic=~\"$topics\",instance=~\"[[instances]]\"}[1m])",
       "legendFormat": "{{topic}}, {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Bytes Rejected Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Bytes Rejected Total Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesrejected_total{job=\"kafka\",topic=~\"$topics\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Rejected Total Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesrejected_total{job=\"kafka\",topic=~\"$topics\",instance=~\"[[instances]]\"}[1m])",
     "legendFormat": "{{topic}}, {{instance}}"
    }
   ]
  },
  { "title": "Replication Bytes In Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Replication Bytes In Total Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesin_total{job=\"kafka\",instance=~\"[[instances]]\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication Bytes Out Total Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesout_total{instance=~\"[[instances]]\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "In-Sync Replica Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Partition In-Sync Replicas Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_cluster_partition_insyncreplicascount{job=\"kafka\",topic=~\"$topics\",instance=~\"[[instances]]\"}",
     "legendFormat": "{{topic}}, {{partition}}, {{instance}}"
    }
   ]
  }
 ]
}