{
 "title": "MongoDB",
 "tags": [
  "prometheus",
  "http-agent"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instancelist",
    "label": "InstanceList",
    "query": "label_values({job=\"mongodb\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "$instancelist Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "repeat": "instancelist",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{instance=~\"$instancelist\"}"
    }
   ]
  },
  {
   "title": "$instancelist Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "repeat": "instancelist",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_connections{state=\"available\",instance=~\"$instancelist\"}"
    }
   ]
  },
  {
   "title": "$instancelist Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "repeat": "instancelist",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_connections{state=\"current\",instance=~\"$instancelist\"}"
    }
   ]
  },
  {
   "title": "Oplog Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_metrics_repl_oplog_insert_total_milliseconds{instance=~\"$instancelist\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$instancelist\"}",
     "legendFormat": "{{ instance }}{{ type }}"
    }
   ]
  },
  {
   "title": "mongodb_metrics_cursor_timed_out_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_metrics_cursor_timed_out_total{instance=~\"$instancelist\"}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_query_executor_total{instance=~\"$instancelist\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "etwork_metrics_num_requests_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_network_metrics_num_requests_total{instance=~\"$instancelist\"}"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$instancelist\"}[5m])",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{instance=~\"$instancelist\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_document_total{instance=~\"$instancelist\"}[5m])",
     "legendFormat": "{{instance}} {{state}}"
    }
   ]
  }
 ]
}