#/bin/bash!
echo "enable demo db sharding"
mongo mongos:40000/admin --eval "sh.enableSharding('demo')"
echo "create collections"
mongo mongos:40000/demo --eval "db.createCollection('records');"
mongo mongos:40000/demo --eval "db.createCollection('activities');"
mongo mongos:40000/demo --eval "db.createCollection('minutes');"
mongo mongos:40000/demo --eval "db.createCollection('joins');"
mongo mongos:40000/demo --eval "db.createCollection('joins_counted');"
echo "shard collections"
mongo mongos:40000/admin --eval "sh.shardCollection('demo.records',{country:1,site:1,product:1});"
mongo mongos:40000/admin --eval "sh.shardCollection('demo.activities',{country:1,site:1,product:1});"
mongo mongos:40000/admin --eval "sh.shardCollection('demo.minutes',{country:1,site:1,product:1});"
echo "create index"
mongo mongos:40000/demo --eval "db.records.createIndex({minute:1});"
mongo mongos:40000/demo --eval "db.activities.createIndex({minute:1});"
mongo mongos:40000/demo --eval "db.minutes.createIndex({minute:1});"
echo "build joins table"
mongo mongos:40000/demo --eval "load('/create_joins_empty.js');"

echo "demo database initiated."
